main-nav:
  - pageid: 1
    url: /index.html
    title: Welcome to Eat4Wellbeing
    img: home_button.jpg

  - pageid: 2
    url: /who-can-benefit.html
    title: Who can benefit?
    img: who_button.jpg

  - pageid: 3
    url: /about-joanna.html
    title: About Joanna
    img: about_button.jpg

  - pageid: 4
    url: /clinic.html
    title: The clinic
    img: clinic_button.jpg

  - pageid: 5
    url: /contact.html
    title: Contact us
    img: contact_button.jpg
    
clinic-nav:
  - pageid: 6
    url: /clinic/consultation.html
    title: The Consultation
    
  - pageid: 7
    url: /clinic/diagnostic-testing.html
    title: Diagnostic Testing

  - pageid: 8
    url: /clinic/testimonials.html
    title: Testimonials

  - pageid: 9
    url: /clinic/price-list.html
    title: Price List

  - pageid: 10
    url: /clinic/location.html
    title: Location
    


htitle: Nutritionist in Brighton
exclude: [tasks]